### ISSUE TITLE
won't get user profile

### ISSUE THREAD

**Issue by Malurth** [UltimaHoarder/UltimaScraper#2076]
tried setting up a partial auth.json and running it, figured the program would elegantly let me know what fields were not up to snuff before exiting. instead it crashed, and now no matter what I seem to do (including deleting the __settings__ and __user_data__ folders) the script will not pick up on any profiles saved in the user data folder; when selecting a profile to use the only option is 0 | All.

no clue how to fix this and I've already been wrestling with this damn thing for hours now

sigh

**Comment by emotional-landfill** [comment]
I'm not overly familiar with Poetry, but it seems like there's a number of missing modules that provide like 99% of the scraper's functionality - it kind of seems like the intention is to have modules pulled from PyPI:

```toml
# `pyproject.toml`:

[tool.poetry.dependencies]
# ...
ultima-scraper-api = "1.1.4"
ultima-scraper-collection = "1.1.3"
ultima-scraper-renamer = "1.1.1"
```

Running  `poetry update` doesn't fix this (which is effectively what `updater.py` does), and manually installing with `pip` also does not work. 

I think the general sentiment is to try another tool for now.
